#!/bin/bash

# Source folder (Local mods folder (curseforge mods location recommended)
A=""

# Server details
SERVER_USER="user"
SERVER_HOST="1.1.1.1"

# Server mods folder
B="/hytale/Server/mods/"   

# Log file
LOG="/hytale/Server/mod_sync_log.txt"

echo "=== MOD SYNC SCRIPT ==="
echo "Syncing local to -> Server ($SERVER_HOST:$B)..."

rsync -av --delete -e ssh "$A" "${SERVER_USER}@${SERVER_HOST}:${B}"

echo "Sync complete."

# Log the sync
echo "[$(date)] Sync A -> Server complete." >> "$LOG"

